version: '3.9'
services:
  mongo:
    image: mongo
    container_name: findex-mongo
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - 27017:27017
    networks:
      - backend
    volumes:
      - /var/mongodb:/data/db

  node_backend:
    container_name: findex-backend
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./frontend:/app/frontend
      - ./log:/app/log
      - ./findex-files:/app/findex-files

    networks:
      - backend

networks:
  backend:
    driver: bridge
